# permissions for end users to edit benchmarks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: benchmark-editor-role
rules:
- apiGroups:
  - cloud.camunda.io
  resources:
  - benchmarks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.camunda.io
  resources:
  - benchmarks/status
  verbs:
  - get
