apiVersion: cloud.camunda.io/v1alpha1
kind: Benchmark
metadata:
  name: benchmark-sample
spec:
  credentialsSecretName: name-of-secret
  workerCount: 2
  processStarterRate: 200
  starterReplicas: 3
  duration: 2m
