apiVersion: v1
kind: Service
metadata:
  labels:
    app: zeebe
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: zeebe-cluster
  name: worker
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9600
      protocol: TCP
      targetPort: 9600
  publishNotReadyAddresses: true
  selector:
    app: worker
  sessionAffinity: None
  type: ClusterIP