apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: {{ or .workerReplicas 3}}
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: gcr.io/zeebe-io/worker:SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: ZEEBE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{or .credentialsSecretName "cloud-credentials" }}
                  key: zeebeAddress
            - name: ZEEBE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{or .credentialsSecretName "cloud-credentials" }}
                  key: clientId
            - name: ZEEBE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{or .credentialsSecretName "cloud-credentials" }}
                  key: clientSecret
            - name: ZEEBE_AUTHORIZATION_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: {{or .credentialsSecretName "cloud-credentials" }}
                  key: authServer
            - name: JAVA_OPTIONS
              value: >-
                -Dzeebe.client.requestTimeout=62000
                -Dapp.tls=true
                -Dapp.worker.capacity=120
                -Dapp.worker.pollingDelay=1ms
                -Dapp.worker.completionDelay=50ms
                -XX:+HeapDumpOnOutOfMemoryError
            - name: LOG_LEVEL
              value: "warn"
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
